
package com.siebel.eqxprocessdartbatches;

import java.net.URL;
import java.util.Properties;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EQX_spcEAI_spcDART_spcBatch_spcProcessing_spcBS", targetNamespace = "http://www.siebel.com/EQXProcessDARTBatches", wsdlLocation = "file:/D:/Equinix/Dart/Tibco%20wsdl/DEV_EQXProcessDARTBatches04182019.wsdl")
@HandlerChain(file="handler-chain.xml")
public class EQXSpcEAISpcDARTSpcBatchSpcProcessingSpcBS_Service
    extends Service
{

    private final static QName EQXSPCEAISPCDARTSPCBATCHSPCPROCESSINGSPCBS_QNAME = new QName("http://www.siebel.com/EQXProcessDARTBatches", "EQX_spcEAI_spcDART_spcBatch_spcProcessing_spcBS");

    private final static URL EQXSPCEAISPCDARTSPCBATCHSPCPROCESSINGSPCBS_WSDL_LOCATION;
    private final static WebServiceException EQXSPCEAISPCDARTSPCBATCHSPCPROCESSINGSPCBS_EXCEPTION;

    static {
    	
        URL url = null;
        WebServiceException e = null;
        try {
        	Properties prop = new Properties();
        	prop.load(EQXSpcEAISpcDARTSpcBatchSpcProcessingSpcBS_Service.class.getClassLoader().getResourceAsStream("application.properties"));
        	String wsdl = prop.getProperty("sbl.wsdllocation");
//            url = EQXSpcProcessSpcDARTSpcBatches.class.getClassLoader().getResource("META-INF/wsdl/EQXProcessDARTBatches04182019.wsdl");//new URL("http://localhost/uat.wsdl");
        	url = EQXSpcEAISpcDARTSpcBatchSpcProcessingSpcBS_Service.class.getClassLoader().getResource(wsdl);//new URL("http://localhost/uat.wsdl");
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        EQXSPCEAISPCDARTSPCBATCHSPCPROCESSINGSPCBS_WSDL_LOCATION = url;
        EQXSPCEAISPCDARTSPCBATCHSPCPROCESSINGSPCBS_EXCEPTION = e;
    }

    public EQXSpcEAISpcDARTSpcBatchSpcProcessingSpcBS_Service() {
        super(__getWsdlLocation(), EQXSPCEAISPCDARTSPCBATCHSPCPROCESSINGSPCBS_QNAME);
    }

    public EQXSpcEAISpcDARTSpcBatchSpcProcessingSpcBS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), EQXSPCEAISPCDARTSPCBATCHSPCPROCESSINGSPCBS_QNAME, features);
    }

    public EQXSpcEAISpcDARTSpcBatchSpcProcessingSpcBS_Service(URL wsdlLocation) {
        super(wsdlLocation, EQXSPCEAISPCDARTSPCBATCHSPCPROCESSINGSPCBS_QNAME);
    }

    public EQXSpcEAISpcDARTSpcBatchSpcProcessingSpcBS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EQXSPCEAISPCDARTSPCBATCHSPCPROCESSINGSPCBS_QNAME, features);
    }

    public EQXSpcEAISpcDARTSpcBatchSpcProcessingSpcBS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EQXSpcEAISpcDARTSpcBatchSpcProcessingSpcBS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EQXSpcEAISpcDARTSpcBatchSpcProcessingSpcBS
     */
    @WebEndpoint(name = "EQX_spcEAI_spcDART_spcBatch_spcProcessing_spcBSSOAP")
    public EQXSpcEAISpcDARTSpcBatchSpcProcessingSpcBS getEQXSpcEAISpcDARTSpcBatchSpcProcessingSpcBSSOAP() {
        return super.getPort(new QName("http://www.siebel.com/EQXProcessDARTBatches", "EQX_spcEAI_spcDART_spcBatch_spcProcessing_spcBSSOAP"), EQXSpcEAISpcDARTSpcBatchSpcProcessingSpcBS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EQXSpcEAISpcDARTSpcBatchSpcProcessingSpcBS
     */
    @WebEndpoint(name = "EQX_spcEAI_spcDART_spcBatch_spcProcessing_spcBSSOAP")
    public EQXSpcEAISpcDARTSpcBatchSpcProcessingSpcBS getEQXSpcEAISpcDARTSpcBatchSpcProcessingSpcBSSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.siebel.com/EQXProcessDARTBatches", "EQX_spcEAI_spcDART_spcBatch_spcProcessing_spcBSSOAP"), EQXSpcEAISpcDARTSpcBatchSpcProcessingSpcBS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EQXSPCEAISPCDARTSPCBATCHSPCPROCESSINGSPCBS_EXCEPTION!= null) {
            throw EQXSPCEAISPCDARTSPCBATCHSPCPROCESSINGSPCBS_EXCEPTION;
        }
        return EQXSPCEAISPCDARTSPCBATCHSPCPROCESSINGSPCBS_WSDL_LOCATION;
    }

}
