
package com.siebel.eqxprocessdartbatches;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EQX_spcEAI_spcDART_spcBatch_spcProcessing_spcBS", targetNamespace = "http://www.siebel.com/EQXProcessDARTBatches")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.siebel.eqxprocessdartbatches.ObjectFactory.class,
    com.siebel.xml.eqx_20dart_20batch_20io.ObjectFactory.class
})
public interface EQXSpcEAISpcDARTSpcBatchSpcProcessingSpcBS {


    /**
     * 
     * @param upsertSpcDARTSpcBatchInput
     * @return
     *     returns com.siebel.eqxprocessdartbatches.UpsertSpcDARTSpcBatchOutput
     */
    @WebMethod(operationName = "Upsert_spcDART_spcBatch", action = "Upsert_spcDART_spcBatch")
    @WebResult(name = "Upsert_spcDART_spcBatch_Output", targetNamespace = "http://www.siebel.com/EQXProcessDARTBatches", partName = "Upsert_spcDART_spcBatch_Output")
    public UpsertSpcDARTSpcBatchOutput upsertSpcDARTSpcBatch(
        @WebParam(name = "Upsert_spcDART_spcBatch_Input", targetNamespace = "http://www.siebel.com/EQXProcessDARTBatches", partName = "Upsert_spcDART_spcBatch_Input")
        UpsertSpcDARTSpcBatchInput upsertSpcDARTSpcBatchInput);

}
