package com.equinix.appops.common;

public final class LogicConstants {
	
	private LogicConstants(){
		
	}
	public static final String SYSTEM = "SYSTEM";
	public static final String ONHOLD = "Hold";
	public static final String SHARED_CAGE = "Shared";
	public static final String PRIVATE_CAGE = "Private";
	public static final String BCTR = "BCTR";
	public static final String COLO = "COLO";
	public static final String CAPACITY_STATUS="CAPACITY_STATUS";
	public static final String UPDATED_BY = "UPDATED_BY";
	public static final String SPACE_CFR_WORKFLOW = "SPACE_CFR_WORKFLOW";
	public static final String POWER_CFR_WORKFLOW = "POWER_CFR_WORKFLOW";
	public static final String AVAILABLE="Available";
	public static final String SPACEANDPOWER_CFR_WORKFLOW = "SPACEANDPOWER_CFR_WORKFLOW";
	public static final String NETWORK_CFR_WORKFLOW = "NETWORK_CFR_WORKFLOW";
	public static final String ANTENNA_CFR_WORKFLOW = "ANTENNA_CFR_WORKFLOW";
	public static final String INNERDUCT_CFR_WORKFLOW = "INNERDUCT_CFR_WORKFLOW";
	public static final String BCTR_CFR_WORKFLOW = "BCTR_CFR_WORKFLOW";
	public static final String WORKFLOW_CFR_AMER_REGION = "WORKFLOW_CFR_AMER_REGION";
	public static final String WORKFLOW_STATUS = "WORKFLOW_STATUS";
	public static final String WORKFLOW_CREATED = "WORKFLOW_CREATED";
	public static final String WORKFLOW_TYPE = "WORKFLOW_TYPE";
	public static final String CREATED_BY = "CREATED_BY";
	public static final String WORKFLOW_TASK_STATUS = "WORKFLOW_TASK_STATUS";
	public static final String IN_PROGRESS = "In Progress";
	public static final String APPROVED = "Approved";
	public static final String RESERVED = "Reserved";
	public static final String REJECTED = "Rejected";
	public static final String BTU_PER_KVA = "BTU_PER_KVA";
	public static final String CAGE_STATUS = "CAGE_STATUS";
	public static final String CAGE_STATUS_ACTIVE = "Active";
	public static final String MERGED = "Merged";
	public static final String SOLD = "Sold";
	public static final String CAGE_AVAILABILITY_STATUS = "CAGE_AVAILABILITY_STATUS";
	public static final String PENDING_AVAILABLE = "Pending Available";
	public static final String INFLIGHT_QUOTE=  "Inflight Quote";
	public static final String CAGE_EARMARKED_STATUS ="CAGE_EARMARKED_STATUS";
	public static final String EARMARKED ="Earmarked";
	public static final String NOT_EARMARKED ="Not Earmarked";
	public static final String CHURN_RESERVED = "Churn-Reserved";
	public static final String RESERVED_PENDING_BUSINESS_APPROVAL = "Reserved Pending Business Approval";
	public static final String RESERVED_PENDING_CFR_APPROVAL = "Reserved Pending CFR Approval";
	public static final String CHURN_SOLD = "Churn-Sold";
	public static final String INSTALLED = "Installed";
	public static final String IMPERIAL = "Imperial";
	public static final String METRIC = "Metric";
	public static final String UNIQUE_SPACE_ID_SEPERATOR = "UNIQUE_SPACE_ID_SEPERATOR";
	public static final String PENDING_AVAILABLE_STAT = "Pending Available";
	public static final String CABINET_AVAILABILITY_STATUS = "CABINET_AVAILABILITY_STATUS";
	public static final String CABINET_WORKFLOW_STATUS="CABINET_WORKFLOW_STATUS";
	public static final String CABINET_STATUS_CHANGE_DATE="CABINET_STATUS_CHANGE_DATE";
	public static final String CABINET_CUSTOMER="CABINET_CUSTOMER";
	public static final String CABINET_RESERVATION="CABINET_RESERVATION";
	public static final String CABINET_PREV_CAPACITY_STATUS ="CABINET_PREV_CAPACITY_STATUS";
	public static final String CABINET_CHURN_CUSTOMER="CABINET_CHURN_CUSTOMER";
	public static final String CABINET_CHURN_RESERVATION="CABINET_CHURN_RESERVATION";
	public static final String CABINET_ASSET_ID="CABINET_ASSET_ID";
	public static final String CABINET_INSTALLED_DATE="CABINET_INSTALLED_DATE";
	public static final String CABINET_DIRECT_ACCESS="CABINET_DIRECT_ACCESS";
	public static final String CABINET_CHURN_DIRECT_ACCESS="CABINET_CHURN_DIRECT_ACCESS";
	public static final String SPACEANDPOWER ="SPACE AND POWER";
	public static final String CABINET_PENDING_AVAILABLE_DATE = "CABINET_PENDING_AVAILABLE_DATE";
	public static final String CABINET_CUSTOMER_REF_NUM = "CABINET_CUSTOMER_REF_NUM";
	public static final String CABINET_INSTALLED_UNIT_IMP_TYPE = "CABINET_INSTALLED_UNIT_IMP_TYPE";
	public static final String CABINET_INSTALLED_UNIT_MT_TYPE = "CABINET_INSTALLED_UNIT_MT_TYPE";
	public static final String CABINET_INSTALLED_KVA = "CABINET_INSTALLED_KVA";
	public static final String CABINET_CBP_INSTALLED = "CABINET_CBP_INSTALLED";
	public static final String CABINET_IS_CONFIGURED = "CABINET_IS_CONFIGURED";
	public static final String CABINET_NUMBER = "CABINET_NUMBER";
	public static final String CABINET_CAGE_NUMBER = "CABINET_CAGE_NUMBER";
	public static final String YES_FLAG = "YES";
	public static final String IS_SPACE_CFR_SIEBEL_INTERFACE_AVAILABLE = "IS_SPACE_CFR_SIEBEL_INTERFACE_AVAILABLE";
	public static final String IS_POWER_CFR_SIEBEL_INTERFACE_AVAILABLE = "IS_POWER_CFR_SIEBEL_INTERFACE_AVAILABLE";
	public static final String IS_SPACE_AND_POWER_CFR_SIEBEL_INTERFACE_AVAILABLE = "IS_SPACE_AND_POWER_CFR_SIEBEL_INTERFACE_AVAILABLE";
	public static final String IS_NETWORK_CFR_SIEBEL_INTERFACE_AVAILABLE = "IS_NETWORK_CFR_SIEBEL_INTERFACE_AVAILABLE";
	public static final String IS_BCTR_CFR_SIEBEL_INTERFACE_AVAILABLE = "IS_BCTR_CFR_SIEBEL_INTERFACE_AVAILABLE";
	public static final String IS_ANTENNA_CFR_SIEBEL_INTERFACE_AVAILABLE = "IS_ANTENNA_CFR_SIEBEL_INTERFACE_AVAILABLE";
	public static final String IS_INNERDUCT_CFR_SIEBEL_INTERFACE_AVAILABLE = "IS_INNERDUCT_CFR_SIEBEL_INTERFACE_AVAILABLE";
	public static final String POF_COLO_DATE_FORMAT = "POF_COLO_DATE_FORMAT";
	public static final String IS_EDITABLE_Y = "Y";
	
	public static final String SPACE_WORKFLOW_NAME = "SPACE_WORKFLOW_NAME";
	public static final String POWER_WORKFLOW_NAME = "POWER_WORKFLOW_NAME";
	public static final String SPACEANDPOWER_WORKFLOW_NAME = "SPACEANDPOWER_WORKFLOW_NAME";
	public static final String ANTENNA_WORKFLOW_NAME = "ANTENNA_WORKFLOW_NAME";
	public static final String BCTR_WORKFLOW_NAME = "BCTR_WORKFLOW_NAME";
	public static final String INNERDUCT_WORKFLOW_NAME = "INNERDUCT_WORKFLOW_NAME";
	public static final String NETWORK_WORKFLOW_NAME = "NETWORK_WORKFLOW_NAME";

	
	public static final String CAGE_WORKFLOW_STATUS="CAGE_WORKFLOW_STATUS";
	public static final String CAGE_STATUS_CHANGE_DATE="CAGE_STATUS_CHANGE_DATE";
	public static final String CAGE_CUSTOMER="CAGE_CUSTOMER";
	public static final String CAGE_RESERVATION="CAGE_RESERVATION";
	public static final String CAGE_PREV_CAPACITY_STATUS ="CAGE_PREV_CAPACITY_STATUS";
	public static final String CAGE_CHURN_CUSTOMER="CAGE_CHURN_CUSTOMER";
	public static final String CAGE_CHURN_RESERVATION="CAGE_CHURN_RESERVATION";
	public static final String CAGE_ASSET_ID="CAGE_ASSET_ID";
	public static final String CAGE_LEGACY_SYSTEM="CAGE_LEGACY_SYSTEM";
	public static final String CABINET_LEGACY_SYSTEM="CABINET_LEGACY_SYSTEM";
	public static final String CAGE_INSTALLED_DATE="CAGE_INSTALLED_DATE";
	public static final String CAGE_DIRECT_ACCESS="CAGE_DIRECT_ACCESS";
	public static final String CAGE_CHURN_DIRECT_ACCESS="CAGE_CHURN_DIRECT_ACCESS";
	public static final String CAGE_PENDING_AVAILABLE_DATE = "CAGE_PENDING_AVAILABLE_DATE";
	public static final String CAGE_INSTALLED_KVA = "CAGE_INSTALLED_KVA";
	public static final String CAGE_CBP_INSTALLED = "CAGE_CBP_INSTALLED";
	public static final String CAGE_ACTUAL_CABINET = "CAGE_ACTUAL_CABINET";
	public static final String CAGE_DESIGNED_CABINET = "CAGE_DESIGNED_CABINET";
	public static final String CAGE_CONFIGURED_CABINET = "CAGE_CONFIGURED_CABINET";
	public static final String CAGE_MAX_NUM_ROWS = "CAGE_MAX_NUM_ROWS";
	public static final String CAGE_MAX_CABS_PER_ROW = "CAGE_MAX_CABS_PER_ROW";
	public static final String CAGE_DRAW_CAP_KVA = "CAGE_DRAW_CAP_KVA";
	public static final String CAGE_DESIGNED_KVA = "CAGE_DESIGNED_KVA";
	public static final String CAGE_PEC_CAP = "CAGE_PEC_CAP";
	public static final String CAGE_AREA_SQ_FEET = "CAGE_AREA_SQ_FEET";
	public static final String CAGE_AREA_SQ_METER = "CAGE_AREA_SQ_METER";
	public static final String CAGE_SALES_SITE_RATING_FROM = "CAGE_SALES_SITE_RATING_FROM";
	public static final String CAGE_SALES_SITE_RATING_TO = "CAGE_SALES_SITE_RATING_TO";
	public static final String CAGE_CIRCUIT_BRK_POS_CAP = "CAGE_CIRCUIT_BRK_POS_CAP";
	public static final String CAGE_MAX_NO_CONDITIONED_CIRCUIT = "CAGE_MAX_NO_CONDITIONED_CIRCUIT";
	public static final String CAGE_MAX_NO_UNCONDITIONED_CIRCUIT = "CAGE_MAX_NO_UNCONDITIONED_CIRCUIT";
	public static final String CAGE_NO_CONDITIONED_CIRCUIT_INSTALLED = "CAGE_NO_CONDITIONED_CIRCUIT_INSTALLED";
	public static final String CAGE_NO_UNCONDITIONED_CIRCUIT_INSTALLED = "CAGE_NO_UNCONDITIONED_CIRCUIT_INSTALLED";
	public static final String CAGE_PUE_CAP = "CAGE_PUE_CAP";
	public static final String CAGE_EARMARKED_TIME = "CAGE_EARMARKED_TIME";
	public static final String CAGE_IS_EDITABLE = "CAGE_IS_EDITABLE";
	public static final String CAGE_MINIMUM_COMMITMENT = "CAGE_MINIMUM_COMMITMENT";
	public static final String TRANSACTIONAL_REPORT_TEMP_LOCATION="TRANSACTIONAL_REPORT_TEMP_LOCATION";
	public static final String TRANSACTIONAL_REPORT_THRESHOLD_SIZE = "TRANSACTIONAL_REPORT_THRESHOLD_SIZE";
	public static final String XLS=".xls";
	public static final String SENDEMAILFAILED="sendEmailFailed";
	public static final String XSLX=".xlsx";
	public static final String XLSX=".xlsx";
	public static final String PDF=".pdf";
	public static final String APPOPS1="APPOPS1";
	public static final String ACTIVE1="ACTIVE";
	public static final String APPOPS2="APPOPS2";
	public static final String APPOPS="APPOPS";
	public static final String CREATE="create";
	public static final String DELETE="delete";
	// added
	public static final String SPACE_CFR_TYPE = "SPACE CFR";
	public static final String POWER_CFR_TYPE="POWER CFR";
	public static final String SPACE_AND_POWER_CFR_TYPE="SPACEANDPOWER CFR";
	public static final String SPACE_GRP="SPACE";
	public static final String POWER_GRP="POWER";
	public static final String SPACE_AND_POWER_GRP="Space And Power";
	public static final String SALES_ENGG_GRP="SALES_ENGG";
	public static final String CSM_GRP="CSM";
	public static final String SITE_TECH_GRP="SITE_TECH";
	public static final String SITE_ENGG_GRP="SITE_ENGG";	
	public static final String SPACE_SALES_ENGG_GRP = "SPACE_SALES_ENGG";
	public static final String POWER_SALES_ENGG_GRP = "POWER_SALES_ENGG";
	public static final String CAGE = "Cage";
	public static final String CUSTOM_OFFICE = "Custom Office";
	public static final String CUSTOM_STORAGE = "Custom Storage";
	public static final String CFR_TYPE = "CFR_TYPE";
	public static final String SPACE_POWER_CFR_TYPE="SPACEANDPOWER";
	public static final String EXCEPTION="Exception ";
	
	public static final String INNERDUCT_CFR_TYPE = "Innerduct";
	public static final String NETWORK_CFR_TYPE = "Network";
	public static final String NETWORK_CFR = "NETWORK CFR";
	public static final String UNAVAILABLE = "Unavailable";
	public static final String QUOTE = "Quote";
	public static final String IBX_DC2 = "DC2";
	public static final String IBX_SG1 = "SG1";
	public static final String IBX_CH1 = "CH1";
	public static final String IBX_CH3 = "CH3";
	public static final String IBX_LD2 = "LD2";
	public static final String IBX_LD5 = "LD5";
	public static final String IBX_SV8 = "SV8";
	public static final String IBX_PA2 = "PA2";
	public static final String NO = "No";
	public static final String YES = "Yes";	
	public static final String Y_FLAG = "Y";
	public static final String N_FLAG = "N";
	public static final String PRIMARY = "Primary";
	public static final String PORT_SPEED_100M = "100M";
	public static final String PORT_SPEED_1G = "1G";
	public static final String PORT_SPEED_10G = "10G";
	public static final String OTHER = "Other";
	public static final String LINK_AGGREGATION = "Link Aggregation";
	public static final String BACKUP = "Backup";
	public static final String QUOTE_TERMINATED = "Quote Terminated";
	public static final String ORDER_BOOKED = "Order Booked";
	public static final String ORDER_CANCELLED = "Order Cancelled";
	public static final String ORDER_COMPLETED = "Order Completed";
	public static final String DELETE_CAPACITY = "Delete Capacity";
	public static final String ORDER_PARTIAL_COMPLETED = "Order Partial Complete";
	public static final String ORDER = "Order";
	public static final String EXPIRED = "Expired";
	public static final int TIMEOUT = 90;
	
	public static final String NETWORKTIMEOUT = "NETWORK_TIMEOUT";
	public static final String FULFILMENT = "Fulfilment";
	public static final String PORT_NOTFOUND = "Port Not found";
	public static final String DEVICE_NOTFOUND = "Device Not found";
	public static final String CFR_REQUIRED = "CFR Required";
	public static final String CFR_APPROVED = "CFR Approved";
	public static final String APPROVED_INITIALLY = "Initial Approved";
	public static final String CFR_INITIATED = "CFR Initiated";
	public static final String CFR_REJECTED = "CFR Rejected";
	public static final String CHECK_CAPACITY = "Check Capacity";
	public static final String RESERVE_CAPACITY = "Reserve Capacity";
	public static final String UPDATED_BY_SYSTEM = "System";
	public static final String CFR_TYPE_NAME_ONEPORT = "Single Port Section";
	public static final String CFR_TYPE_NAME_TWOPORT = "Two Port Section";
	public static final String LAMBDA = "lambda";
	public static final String CFR_TYPE_NAME_COMMIT_POE = "Minimum Bandwidth Commit PoE Section";
	public static final String CFR_TYPE_NAME_DOMESTIC_TRAFFIC = "Minimum Bandwidth Commit Domestic Traffice Section";
	public static final String CFR_TYPE_NAME_DOWNLOAD_TRAFFIC = "Download Traffic Plan Section";
	public static final String CFR_TYPE_NAME_ADDITIONAL_IP = "Additional IP Allocation";
	public static final String RESERVE_NOT_SUPPORTED = "Reserve Port not Supported";
	public static final String CFR_REJECTED_QUOTE_REVERSION = "Rejected Due to Quote Reversion";
	public static final String CANCELLATION_NOT_SUPPORTED = "No Cancellation can be done at Fulfillment level";
	public static final String CFR_REJECTED_DUETO_CANCEL_EXPIRY_REJECTED = "CFR rejected due to expiry or cancel or rejected message from Siebel.";
	public static final String CIRCUIT_TYPE = "CIRCUIT_TYPE";
	public static final String CIRCUIT_TYPE_ID = "CIRCUIT_TYPE_ID";
	public static final String CIRCUIT_ADD = "Add";
	public static final String CIRCUIT_DELETE = "Delete";
	public static final String CIRCUIT_CAB_DRAW_CAP_FAILURE = "Configured circuit violates Cabinet Draw Cap Kva value";
	public static final String CIRCUIT_CAB_CBP_FAILURE = "Configured circuit violates Cabinet Circuit Breaker Position Value";
	public static final String CIRCUIT_CAGE_DRAW_CAP_FAILURE = "Configured circuit violates Cage Draw Cap Kva value";
	public static final String CIRCUIT_CAGE_CBP_FAILURE = "Configured circuit violates Cage Circuit Breaker Position Value";
	
	public static final String ANTENNA_TYPE = "ANTENNA_TYPE"; 
	public static final String INNERDUCT_MEDIA_TYPE = "INNERDUCT_MEDIA_TYPE";
	public static final String PATCH_PD_MEDIA_TYPE = "PATCH_PD_MEDIA_TYPE";
	public static final String INSTALL_TYPE = "INSTALL_TYPE";
	public static final String ANTENNA_SIZE = "ANTENNA_SIZE";
	public static final String QUOTE_TYPE = "QUOTE_TYPE"; 
	public static final String BCTR_ROOM_TYPE = "BCTR_ROOM_TYPE";
	public static final String EXCEPTION_CODE_256 = "CL-256";
	public static final String EXCEPTION_CODE_255 = "CL-255";
	public static final String EXCEPTION_CODE_209 = "CL-209";
	public static final String EXCEPTION_CODE_210 = "CL-210";
	public static final String EXCEPTION_CODE_109 = "CL-109";
	public static final String EXCEPTION_CODE_200 = "CL-200";
	public static final String EXCEPTION_CODE_204 = "CL-204";
	public static final String EXCEPTION_CODE_206 = "CL-206";
	public static final String EXCEPTION_CODE_205 = "CL-205";
	public static final String EXCEPTION_CODE_207 = "CL-207";
	public static final String EXCEPTION_CODE_208 = "CL-208";
	public static final String EXCEPTION_CODE_232 = "CL-232";
	public static final String EXCEPTION_CODE_238 = "CL-238";
	public static final String EXCEPTION_CODE_239 = "CL-239";
	public static final String EXCEPTION_CODE_240 = "CL-240";
	public static final String EXCEPTION_CODE_242 = "CL-242";
	public static final String EXCEPTION_CODE_300 = "CL-300";
	public static final String EXCEPTION_CODE_334 = "CL-334";
	public static final String EXCEPTION_CODE_502 = "CL-502";
	public static final String EXCEPTION_CODE_503 = "CL-503";
	public static final String EXCEPTION_CODE_505 = "CL-505";
	public static final String EXCEPTION_CODE_506 = "CL-506";
	public static final String EXCEPTION_CODE_507 = "CL-507";
	public static final String EXCEPTION_CODE_508 = "CL-508";
	public static final String EXCEPTION_CODE_509 = "CL-509";
	public static final String EXCEPTION_CODE_510 = "CL-510";
	public static final String EXCEPTION_CODE_233 = "CL-233";
	public static final String EXCEPTION_CODE_235 = "CL-235";
	public static final String EXCEPTION_CODE_313 = "CL-313";
	public static final String EXCEPTION_CODE_314 = "CL-314";
	public static final String EXCEPTION_CODE_020 = "CL-020";
	public static final String EXCEPTION_CODE_113 = "CL-113";
	public static final String EXCEPTION_CODE_112 = "CL-112";
	public static final String EXCEPTION_CODE_212 = "CL-212";
	public static final String EXCEPTION_CODE_213 = "CL-213";
	public static final String EXCEPTION_CODE_215 = "CL-215";
	public static final String EXCEPTION_CODE_273 = "CL-273";
	public static final String EXCEPTION_CODE_220 = "CL-220";
	public static final String EXCEPTION_CODE_221 = "CL-221";
	public static final String EXCEPTION_CODE_110 = "CL-110";
	public static final String EXCEPTION_CODE_214 = "CL-214";
	public static final String EXCEPTION_CODE_217 = "CL-217";
	public static final String EXCEPTION_CODE_161 = "CL-161";

	public static final String EXCEPTION_CODE_219 = "CL-219";
	public static final String EXCEPTION_CODE_335 = "CL-335";

	public static final String EXCEPTION_CODE_331 = "CL-331";
	public static final String EXCEPTION_CODE_218 = "CL-218";
	public static final String EXCEPTION_CODE_301 = "CL-301";
	public static final String EXCEPTION_CODE_501 = "CL-501";
	public static final String EXCEPTION_CODE_321 = "CL-321";
	public static final String EXCEPTION_CODE_332 = "CL-332";
	public static final String EXCEPTION_CODE_134 = "CL-134";
	public static final String EXCEPTION_CODE_258 = "CL-258";

	
	
	public static final int ZERO = 0;
	public static final int ONE = 1;
	public static final int TWO = 2;
	public static final int THREE = 3;
	public static final int FOUR = 4;
	public static final int FIVE = 5;
	public static final int SIX = 6;
	public static final int TEN = 10;
	public static final int FIFTEEN = 15;
	public static final int HUNDRED = 100;
	public static final int FIFTY = 50;
	public static final int FIFTY_FIVE = 55;
	
	// Secure Cabinet
	public static final boolean TRUE_FLAG = true;
	public static final boolean FALSE_FLAG = false;
	public static final String TRUE = "true";
	public static final String FALSE = "false";
	public static final String INFLIGHT_CFR_REASON = "Power CFR is required for this type of Quote";
	public static final String IBX_ENFORCE_CFR_REASON = "#IBX# is enforced for Space/Power CFR";
	public static final String SPACE_RESTRICT_CFR_REASON = "Site Restricted for Space";
	public static final String POWER_RESTRICT_CFR_REASON = "Site Restricted for Power";
	public static final String SPACE_DEAL_CFR_REASON = "Deal exceeds Space threshold";
	public static final String POWER_DEAL_CFR_REASON = "Deal exceeds Power threshold";
	public static final String CFR_RESON_APPENDER = ".";
	public static final String PRODUCT_TYPE_SHARED = "Shared";
	public static final String PRODUCT_TYPE_PRIVATE = "Private";
	public static final String PRODUCT_TYPE_IBX_FLEX = "IBX Flex";
	public static final String CABINET_TYPE = "CABINET_TYPE";
	public static final String CABINET_EARMARKED_STATUS ="CABINET_EARMARKED_STATUS";
	public static final String PRODUCT_TYPE = "PRODUCT_TYPE";
	public static final String WORKSPACE_TYPE = "WORKSPACE_TYPE";
	public static final String EXCEPTION_CODE_111 = "CL-111";
	public static final String EXCEPTION_CODE_223 = "CL-223";
	public static final String N = "N";
	public static final String Y = "Y";
	public static final String HYPHEN = "-";
	public static final String EARMARKED_TIME = "EarmarkedTime";
	public static final String ACTIVE = "Active";
	public static final String STATUS = "status";
	public static final String CHURN_CUSTOMER = "churnCutomer";
	public static final String CHURN_RESERVATION = "churnReservation";
	public static final String CHURN_DIRECT_ACCESS_CC = "churnDirecetAccessCrossConnect";
	public static final String ASSET_ID = "assetId";
	public static final String ASSET_ID_1 = "assetId1";
	public static final String ASSET_ID_2 = "assetId2";
	public static final String ASSET_ID_3 = "assetId3";
	public static final String ASSET_ID_4 = "assetId4";
	
	public static final String INSTALLED_DATE = "installDate";
	public static final String INSTALLED_DATE_1 = "installDate1";
	public static final String INSTALLED_DATE_2 = "installDate2";
	public static final String INSTALLED_DATE_3 = "installDate3";
	public static final String INSTALLED_DATE_4 = "installDate4";
	
	public static final String CUST_CAB_REF_NUM = "customerCabRefNo";
	public static final String INSTALL_UNIT_METRIC = "installedUnitMTType";
	public static final String INSTALL_UNIT_IMPERIAL = "installedUnitImpType";	
	public static final String IS_CONFIGURED = "isConfigured";
	
	public static final String CUSTOMER_SEGMENT ="CUSTOMER_SEGMENT";
	public static final String CUSTOMER_SUB_SEGMENT = "CUSTOMER_SUB_SEGMENT";
	public static final String CUSTOMER_SUB_SUB_SEGMENT = "CUSTOMER_SUB_SUB_SEGMENT";
	public static final String POWER ="POWER";
	public static final String SPACE ="SPACE";
	public static final String OPS_SUPPORT ="OPS_SUPPORT";
	public static final String SUCCESS = "success";
	public static final String CABINET = "Cabinet";
	public static final String CUSTOMER_NAME = "customerName";
	public static final String RESERVATION_ID = "reservationId";
	public static final String CAPACITY_STATUS_ID = "capacityStatusId";
	public static final String KVA_INSTALLED = "installedKva";
	public static final String CBP_INSTALLED = "circuitBrkPositionInstalled";
	public static final String WORKSTATION = "WorkStation";
	public static final String NA = "N/A";
	public static final String EARMARKED_THRESHOLD = "EARMARKED_THRESHOLD";
	public static final String RESTRICTED_SEGMENT_CUSTOMER = "RESTRICTED_SEGMENT_CUSTOMER";
	public static final String NEW_CUSTOMER = "New Customer";
	public static final String CAPACITY_STATUS_AUDIT = "CAPACITYSTATUS";
	
	public static final String COLO_ORDER_BOOKED_SUBJECT = "COLO_ORDER_BOOKED_SUBJECT";
	public static final String COLO_ORDER_CANCELLED_SUBJECT = "COLO_ORDER_CANCELLED_SUBJECT";
	public static final String COLO_ORDER_COMPLETED_SUBJECT = "COLO_ORDER_COMPLETED_SUBJECT";
	
	
	public static final String GRX_REQUEST_POFID="MOB00001.PROD";
	public static final String INTERNET_EXCHANGE="IX00001.PROD";
	public static final String INTERNET_EXCHANGE_REMOTE_POFID="IX00002.PROD";
	public static final String GRX_METRO_REMOTE_REQUEST_POFID="MOB00002.PROD";
	public static final String ETHERNET_EXCHANGE_POFID="ETH00001.PROD";
	public static final String ETHERNET_EXCHANGE_REMOTE_POFID="ETH00002.PROD";
	public static final String NETWORK_TIMING_POFID="NT00001.PROD";
	public static final String EXTENDED_METRO_CONNECT_PROTECTED_POFID="EXT00003.PROD";
	public static final String EXTENDED_METRO_CONNECT_UNPROTECTED_POFID="EXT00005.PROD";
	public static final String METRO_CONNECT_PROTECTED_POFID="MC00002.PROD";
	public static final String METRO_CONNECT_UNPROTECTED_POFID="MC00001.PROD";
	public static final String EQUINIXCONNECT_REQUEST_POFID="EC00001.PROD";
	public static final String EQUINIXCONNECT_METRO_REMOTE_REQUEST_POFID="EC00002.PROD";
	public static final String ETHERNET_EXCHANGE_VMMR_SP_REQUEST_POFID="ETH00006.PROD";
	public static final String ETHERNET_EXCHANGE_VMMR_P2P_REQUEST_POFID="ETH00005.PROD";
	public static final String INTERNET_EXCHANGE_METRO_REMOTE_REQUEST_POFID="IX00003.PROD";
	public static final String EXTENDED_METRO_CONNECT_REDUNDANT_REQUEST_POFID="EXT00004.PROD";
	public static final String METRO_CONNECT_REDUNDANT_REQUEST_POFID="MC00003.PROD";
	public static final String ETHERNET_EXCHANGE_METRO_REMOTE_REQUEST_POFID="ETH00004.PROD";
	public static final String PARTNER_IX_METRO_REMOTE_REQUEST_POFID="IX00006.PROD";
	public static final String EQUINIX_CONNECT_PROVIDER_INDEPENDENT_ADDRESS_SPACE_REQUEST_POFID="EC00005.PROD";
	public static final String EQUINIX_MANAGEMENT_ACCESS_REQUEST_POFID="EMA00001.PROD";
	public static final String VMMRSDH_VTRANS_POFID="V00006.PROD";
	public static final String VMMRSDH_PORTS_POFID="V00001.PROD";
	public static final String VOIP_TDM="V00002.PROD";
	public static final String INNERDUCT_POFID="EXT00006.PROD";
	public static final String EQUINIX_ETHERNET_EXCHANGE_EXTENTED_METRO_REMOTE_PORT_POFID="ETH00004.PROD";
	public static final String EQUINIX_ETHERNET_EXCHANGE_METRO_REMOTE_PORT_POFID="ETH00003.PROD";

	public static final String EQUINIX_INTERNET_EXCHANGE_PRIVATE_VLAN_POFID="IX00007.PROD";
	public static final String VOIP_VPEER_EXTENSION="V00004.PROD";
	
	public static final String REQUEST_TYPE_NEW="Add";
	public static final String REQUEST_TYPE_DELETE="Delete";
	public static final String REQUEST_TYPE_UPDATE="Update";
	public static final String REQUEST_TYPE_DASH="-";
	public static final String DASH="-";
	public static final String SLASH="/";
	public static final String REQUEST_TYPE_RESERVE="Reserve";
	public static final String TESTUSER = "Test User";
	public static final String ADMIN_EMAIL_ID="ADMIN_EMAIL_ID";
	public static final String LOCKED_STATUS="LOCKED_STATUS";
	public static final String BUSINESS_SUITE="Business Suite";
	public static final long BUSINESS_SUITE_PK_ID=6L;
	public static final String CABINET_TYPE_ANTENNA_MAST = "Antenna Mast";
	public static final String CABINET_TYPE_FULL = "Full Cabinet";
	public static final String CABINET_TYPE_HALF = "Half Cabinet";
	public static final String CABINET_TYPE_QUARTER = "Quarter Cabinet";
	public static final String CABINET_TYPE_EIGHTH = "Eighth Cabinet";
	public static final String CABINET_TYPE_DEMARC = "Demarc";

	public static final String ANTENNA_SUBJECT_LINE = "ANTENNA_SUBJECT_LINE";	
	public static final String QUOTE_ID="quoteId";
	public static final String QUOTE_LINE_ITEM_ID="quoteLineItemId";
	public static final String UNIQUE_SPACEID_DELETE="uniqueSpaceIdDelete";
	public static final String CAB_NUM_DELETE="cabinetNumDelete";
	public static final String IBXSPRRESERVED = "IBX-SPR-Reserved";
	public static final String IBXSPRSOLD = "IBX-SPR-Sold";	
	public static final String IBXSPRINSTALLED = "IBX-SPR-Installed";	
	public static final String CHURN_IBXSPRRESERVED = "Churn-IBXSPRReserved";
	public static final String CHURN_IBXSPRSOLD = "Churn-IBXSPRSold";
	

	//IBX Flex
	public static final String IBX_FLEX_WORKSPACE_CFR = "WorkSpaceType needs a Space CFR";
	public static final String IBX_FLEX_CONDITIONED_CIRCUIT = "Space and Power CFR is needed as Number Of Conditioned circuits are greater than 0";
	public static final String IBX_FLEX_UNCONDITIONED_CIRCUIT = "Space and Power CFR is needed as Number Of UnConditioned circuits are greater than 0";
	public static final String IBX_FLEX_CONDITIONED_CIRCUIT_TYPE = "Conditioned";
	public static final String IBX_FLEX_UNCONDITIONED_CIRCUIT_TYPE = "Unconditioned";
	public static final String IBX_FLEX_INVALID_CIRCUIT_REASON = "Number of Conditioned/Unconditioned circuits requested exceeds Number of Conditioned/Unconditioned ciruits Installed";
	
	
	
	//colo Service constants
	public static final String POF_ID_1_0 = "BS00001.PROD";
	public static final String POF_ID_2_0 = "BS00003.PROD";
	public static final String POF_ID_3_0 = "SPC00009.PROD";
	public static final String POF_ID_4_0 = "FLEX00001.PROD";
	public static final String POF_ID_5_0 = "SPC00001.PROD";
	public static final String POF_ID_6_0 = "SPC00002.PROD";
	public static final String POF_ID_7_0 = "SPC00004.PROD";
	public static final String POF_ID_8_0 = "SPC00003.PROD";
	public static final String POF_ID_9_0 = "SPC00005.PROD";
	public static final String POF_ID_10_0 = "SPC00006.PROD";
	public static final String POF_ID_11_0 = "SPC00008.PROD";
	public static final String POF_ID_12_0 = "SPC00007.PROD";
	public static final String POF_ID_13_0 = "13.0";
	public static final String POF_ID_14_0 = "EXT00006.PROD";
	public static final String POF_ID_15_0 = "ANT00001.PROD";
	public static final String POF_ID_16_0 = "BC00001.PROD";
	public static final String POF_ID_17_0 = "BS00002.PROD";

    public static final String POSITIONS="Positions";
    public static final String CUST_ID="customerId";
    public static final String CUST_ID_1="customerID1";
    public static final String CUST_ID_2="customerID2";
    public static final String CUST_ID_3="customerID3";
    public static final String CUST_ID_4="customerID4";
    public static final String AVAILABLITY_STATUS="availabilityStatus";
    public static final String AVAIL_STATUS_1="availabilityStatus1";
    public static final String AVAIL_STATUS_2="availabilityStatus2";
    public static final String AVAIL_STATUS_3="availabilityStatus3";
    public static final String AVAIL_STATUS_4="availabilityStatus4";
    public static final String RES_ID="reservationId";
    public static final String RES_ID_1="reservationID1";
    public static final String RES_ID_2="reservationID2";
    public static final String RES_ID_3="reservationID3";
    public static final String RES_ID_4="reservationID4";

	public static final String POF_NEW_REQUEST = "New Request";
	public static final String POF_DELETE_CAGE_REQUEST = "Delete";
	public static final String POF_DELETE_CABINET_REQUEST = "Delete";
	public static final String POF_DELETE_POWER_CIRCUIT_REQUEST = "Delete";
	public static final String POF_ADD_CABINET_REQUEST = "Add Cabinet";

	public static final String POF_UPDATE_REQUEST = "Update";
	public static final String POF_ADD_REQUEST = "ADD";
	public static final String POF_DELETE_REQUEST = "Delete";
	
	

    public static final String CAGE_CAPACITY_STATUS = "CapacityStatusId";
    public static final String WKFLOW_STATUS = "WorkFlowStatusId";
    public static final String STATUS_CHANGE_DATE = "statusChangeDate";
    public static final String POF_NAME = "PofName";
    public static final String RESERVATION = "Reservation";
    public static final String CUSTOMER = "Customer";
    public static final String WORKFLOW_STATUS_ID = "WorkFlowStatusId";
    public static final String DIRECT_ACCESS_CC = "DirectAccessCrossConnect";
    public static final String POF= "Pof";
    public static final String PREVIOUS_AVAILABLE_STATUS = "PrevAvailableStatus";
    public static final String EDITABLE= "IsEditable";
    public static final String PENDING_AVAILABLE_DATE = "pendingAvailableDate";
    
    public static final String QUOTE_ID_NULL= "Request QuoteId is null";
    public static final String IBX_CODE_START="<ibxCode>";
    public static final String IBX_CODE_END= "</ibxCode>";
    public static final String IBX_SITE_RESTRICTED_QUEUE= "ibxSiteRestrictedCheckQueue";
    public static final String SUBREGION_NA= "NA";
    public static final String SUBREGION_EU= "EU";
    public static final String SUBREGION_AP= "AP";
    public static final String YES_IN_CAPS = "YES";
    public static final String NO_IN_CAPS = "NO";
    public static final String CFR_TYPE_POWER = "Power";
    public static final String CFR_TYPE_SPACE = "Space";
    public static final String CFR_TYPE_SPACE_POWER = "Space/Power";

    public static final String CAGE_DRAW_MAX_CHECK_CONFIG_REASON = "No more circuits can be added to the Cage";
    public static final String DOUBLE_0 = "0.0";
    public static final String LONG_0 = "0";
    public static final String CIRCUIT_TYPE_AC = "AC";
    public static final String CIRCUIT_TYPE_DC = "DC";

    public static final String ANTENNA= "Antenna";
    public static final String TEXT_HTML = "text/html";
    

    public static final String ZERO_VAL = "0.0";
    public static final String CABINET_DRAW_MAX_CHECK_CONFIG_REASON = "No more circuits can be added to the #CABNUMBER#";
    
    public static final String EXCEPTION_MESSAGE ="Exception message";
    
    public static final String LOADTRACK_INTERFACE = "LOADTRACK_INTERFACE";
    
    public static final String AUDIT_TYPE_EXCEPTION = "Exception";
    public static final String QOS_AUDIT = "QOS_AUDIT";
    public static final String FLAG_ON = "ON";
    public static final int QOSEXCEP_STRING_LENGTH=4000;
    public static final String SPACE_CFR_MESSAGE = "Approve SpaceCFR Exception ";
    public static final String ANTENNA_CFR_MESSAGE = "Approve AntennaCFR Exception ";
    
    public static final String PRIMARY_CIRCUIT = "Primary";
    public static final String REDUNDANT_CIRCUIT = "Redundant";
    public static final String UNCONDITIONED_CIRCUIT = "Unconditioned";
    public static final String SUCCESS_CAPS = "Success";
    public static final String FAILURE_CAPS = "Failure";
    public static final String PRIM_RED_CIRCUIT_CAGE_FAILURE = "Number of Redundant circuits greater than Primary Circuits at Cage";
    public static final String PRIM_RED_CIRCUIT_CABINET_FAILURE = "Number of Redundant circuits requested greater than the number of Primary Circuits requested for Cabinet ";
    public static final String PRIM_RED_KVA_CAGE_FAILURE = "Useable Kva of Redundant Circuits greater than primary Circuits at Cage";
    public static final String PRIM_RED_KVA_CABINET_FAILURE = "Useable Kva of Redundant Circuits requested greater than kva of primary Circuits requested for Cabinet ";
    public static final String CIRCUIT_NOT_FOUND = "No matching circuits found";
    public static final String CABINET_CONFIGURED_LIST_ERROR = "#CABNUMBER# is not present in configured Cabinet List";
    public static final String CABINET_DOES_NOT_EXIST_ERROR = "#CABNUMBER# does not exist in the Cage";
    public static final String CAGE_DOES_NOT_EXIST_ERROR = "#UNIQID# does not exist in AppOps";
    public static final String IBX_FLEX_POWER_SALES_RATING_ERROR = "Sum of Installed and Requested power should be within Sales Rating";
    public static final String CONFIG_POWER_SALES_RATING_ERROR = "Sum of Installed and Requested power should be within Sales Rating";
    public static final String CFR_TYPE_ANTENNAE = "Antenna";
    public static final String CFR_TYPE_BCTR = "BCTR";
    
	public static final String ERROR_MESSAGE = "Error in Publishing message to ibxSiteResrictedCheckQueue";
	public static final String AUDIT_SENDER_QUEUE = "auditSenderQueue";
	public static final String QOS_AUDIT_SENDER_QUEUE = "qosAuditSenderQueue";
	public static final String EMAIL_MESSAGE_SENDER_QUEUE = "emailMessageSenderQueue";
	public static final String EMS_MESSAGE_SENDER_QUEUE = "emsMessageSenderQueue";
	public static final String CFR_RESPONSE_SENDER_QUEUE = "cfrResponseSenderQueue";
	public static final String TIBCO_ASYC_ACK_RESPONSE_SENDER_QUEUE = "tibcoAsynAckResponseQueue";
	public static final String ACCOUNT_CROSS_REFERENCE_SENDER_QUEUE = "accountCrossReferenceSenderQueue";
	public static final String UNIQUE_SPACEID_MESSAGE_SENDER_QUEUE = "uniqueSpaceIdMessageSenderQueue";
	public static final String QUEUE = " Queue @@@@@@@@@@@  : ";
	public static final String SENT_MESSAGE = "Sent message to";
	public static final String CAGE_NUM_CFR_REASON = "Cage provided does not match conditions";
	public static final String VENDOR = "VENDOR";
	public static final String TIME_SERVICE_SUPPORTED = "TIME_SERVICE_SUPPORTED";
	// Antenna CFR Response
	
	public static final String CFR_RESPONSE ="EQXCFRStatus";
	public static final String ANTENNA_TYP ="Antenna Type";
	public static final String AZIMUTH = "Azimuth";
	public static final String ANT_SIZE = "Antenna Size";
	public static final String CAB_NUM_ANTENNA_MAST = "cabinetNumberAntennaMast";
	public static final String CAB_UNIQUE_SPACE_ID_ANTENNA_MAST= "EQXCabinetUniqueSpaceId";
	public static final String CAB_UNIQUE_SPACE_ID_VALUE_ANTENNA_MAST = "cabinetUniqueSpaceIdValueAntennaMast";
	public static final String CABLE_PROVIED_EQUINIX ="Cable provided by Equinix";
	public static final String CABLE_TYPE ="Antenna Cable Type";
	public static final String CAGE_NUM_ROOF_SPACE = "cageNumberofRoofSpace";
	public static final String CONNECTION_TYPE = "Connector Type";
	public static final String CUSTOM_WORK_DESCRIPTION = "Custom Work Description";
	public static final String CUSTOM_WORK_REQUIRED= "Custom Work Required";
	public static final String ELEVATION ="Elevation";
	public static final String FREQUENCY ="Frequency";
	public static final String FREQUENCY_USE_LICENSE_REQUIRED ="Frequency Use License Required?";
	public static final String IBX ="ServiceAccount";
	public static final String INSTALLATION_TYPE ="Installation Type";
	public static final String NOTES ="EQXCFRDescription";
	public static final String NUM_OF_CURCUITS ="Number of Circuits";
	public static final String PATCH_PANEL_DEDICATED_MEDIA_TYPE="Patch Panel Dedicated Media Type";
	public static final String PATCH_PANEL_MAXIMUM_PORTS ="Patch Panel Maximum Ports";
	public static final String POWER_REQUIRED ="Power Required";
	public static final String POWER_TYPE="Power Type";
	public static final String PROPOSED_LABOR_HOURS ="Proposed Labor Hours";
	public static final String PROPOSED_PARTS_COST ="Proposed Parts Cost";
	public static final String UNIQUE_SPACE_ID_ROOF_SPACE ="EQXCageUniqueSpaceId";
	public static final String UNIQUE_SPACE_ID_VALUE_ROOF_SPACE ="uniqueSpaceIDValueofRoofSpace";
	
	// COLO CFR Response
	
	public static final String AVAILABLE_STATUS ="EQXCapacityStatus";
	public static final String UNIQUE_SPACE_ID_CAGE ="uniqueSpaceId";
	public static final String UNIQUE_SPACE_ID_VALUE_CAGE ="uniqueSpaceIdValue";
	public static final String CAGE_NUMBER ="cageNumber";
	public static final String CABINET_RATING_KVA ="cabinetRatingKVA";
	public static final String SIZE ="Size";
	public static final String AVG_CABINET_RATING="Average Cabinet Rating";
	public static final String AVG_CABE_RATING="Average CabE Rating";
	public static final String NO_OF_ROWS="Max Number of Rows";
	public static final String DRAW_CAP_KVA="Draw Cap (KVA)";
	public static final String NO_OF_CABE_PER_ROW="Max Number of Cabinet Equivalents per Row";
	public static final String TOTAL_CAGE_DESIGN_KVA="Total Cage Design (KVA)";
	public static final String PUE_CAP="PUE Cap";
	public static final String MIN_COMMITMENT="minCommitment";
	public static final String DIRECT_ACCESS_CROSS_CONNECT="directAccessCrossConnect";
	public static final String MAX_CABINET_EQUIVALENTS="Max Cabinet Equivalents";
	public static final String CIRCUIT_BREAKER_POSITIONS_CAP="Circuit Breaker Positions Cap (CBP)";
	public static final String MAX_NO_OF_CONDITION_CIRCUITS="maxNoOfConditionCircuits";
	public static final String MAX_NO_OF_UNCONDITION_CIRCUITS="maxNoOfUnConditionedCircuits";
	public static final String NO_OF_CONDITION_CIRCUITS_INSTALLED="noOfConditionedCircuitsInstalled";
	public static final String NO_OF_UNCONDITION_CIRCUITS_INSTALLED="noOfUnConditionedCircuitsInstalled";
	public static final String TOTAL_AC_DC_POWER_KVA_CONTRACTED="totalACDCPowerKVAContracted";
	public static final String CIRCUIT_BREAKER_POSITIONS_INSTALLED="Circuit Breaker Positions Installed";
	public static final String TOTAL_USEABLE_KVA_INSTALLED="Useable kVA Installed";
	public static final String IBX_SALES_RATING_RANGE="iBXSalesRatingRange";
	public static final String CABINET_EQUIVALENTS="# Cabinets Equivalents";
	public static final String ACTUAL_DRAW="Actual Draw kVA";
	public static final String PEC_CAP="PEC Cap";
	public static final String MAX_NO_OF_CONDITION_CIRCUITS_IBXFLEX="Max # of Condition Circuits";
	public static final String MAX_NO_OF_UNCONDITION_CIRCUITS_IBXFLEX="Max # of uncondition Circuits";
	public static final String NO_OF_CONDITION_CIRCUITS_INSTALLED_IBXFLEX="# of Condition Circuits Installed";
	public static final String NO_OF_UNCONDITION_CIRCUITS_INSTALLED_IBXFLEX="# of uncondition Circuits Installed";	
	
			//POE PART Number starts...
			public static final String POE_ACPOWER_PART_NUMBER = "POW00001.ELEM";
			public static final String POE_CABINET_PART_NUMBER = "CAB00001.ELEM";
			public static final String POE_CAGE_PART_NUMBER = "CAG00001.ELEM";	
			public static final String POE_WS_PART_NUMBER = "BC00002.ELEM";	
			public static final String POE_CARBONLEVY_PART_NUMBER = "POW00005.ELEM";
			public static final String POE_DCPOWER_PART_NUMBER = "POW00002.ELEM";
			public static final String POE_RECTIFIERSHELF_PART_NUMBER = "POW00009.ELEM";
			public static final String POE_ANTENNA_PART_NUMBER = "ANT00001.ELEM";
			public static final String POE_BCTR_PART_NUMBER = "BC00001.ELEM";
			public static final String POE_DEMARCATIONPOINT_PART_NUMBER = "CC00004.ELEM";
			public static final String POE_IBXFLEXCFR_PART_NUMBER = "SPC00001.ELEM";
			public static final String POE_PATCHPANEL_PART_NUMBER = "CC00001.COMP";
			public static final String POE_DEMACATIONPOINT_PART_NUMBER = "CC00004.ELEM";
			
			
			public static final String QUOTE_REQUEST_URI = "xmlns:ns2=\"http://www.equinix.com/appops/integration/quote/request/schema/v1_0\"";
			public static final String QUOTE_RESPONSE_URI = "xmlns=\"http://www.equinix.com/appops/integration/quote/response/schema/v1_0\" xmlns:ns2=\"http://www.equinix.com/appops/integration/quote/response/schema/v1_0\"";
			
			
			
	
			
   public static final String CFR_RESPONSE_OR_CFR_STATUS = "EQXCFRStatus";
   public static final String SERVICE_ACCOUNT="ServiceAccount";
   public static final String SWITCH_NAME_INSTANCE_ID="Switch Name Instance ID";
   public static final String SWITCH_MODULE_INSTANCE_ID="Switch Module Instance ID";
   public static final String SWITCH_PORT_INSTANCE_ID="Switch Port Instance ID";
   public static final String SWITCH_SHELF_INSTANCE_ID="Switch Shelf Instance ID";
   public static final String SWITCH_SLOT_INSTANCE_ID="Switch Slot Instance ID";
   public static final String SWITCH_NAME="Switch Name";
   public static final String SWITCH_MODULE="Switch Module";
   public static final String SWITCH_PATCH_PANEL="Switch-Patch Panel";
   public static final String SWITCH_PORTA="Switch-Port A";
   public static final String SWITCH_PORTB="Switch-Port B";
   //public static final String PART_NUMBER="";
   //public static final String POE_NAME="";
   public static final String SWITCH_PORT="Switch Port";
   public static final String SWITCH_SHELF="Switch Shelf";
   public static final String SWITCH_SLOT="Switch Slot";
   public static final String CUSTOMER_ACCOUNT_TYPE="CUSTOMER_ACCOUNT_TYPE";
   public static final String CUSTOMER_ACCOUNT_STATUS="CUSTOMER_ACCOUNT_STATUS";
   public static final String CFR_REASON_REJECT="EQXCFRRejectionReason";
   
   public static final String ORDER_CANCEL_CABINET_UNQIEU_SPACE_ID_NAME = "EQXCABINETUSID";
   public static final String ORDER_CANCEL_CIRCUIT_AMPS = "Sold Amperage";
   public static final String ORDER_CANCEL_CIRCUIT_VOLTS = "Voltage";
   public static final String ORDER_CANCEL_CIRCUIT_PHASE = "Phase";
   public static final String ORDER_CANCEL_CIRCUIT_CABINET_NUMBER = "Cabinet Number";
   public static final String ORDER_CANCEL_DEMARC_CABINET_NUMBER = "Cabinet Number";
   public static final String ORDER_CANCEL_AC_CIRCUIT_PARTNUMBER = "POW00003.ELEM";
   public static final String ORDER_CANCEL_DC_CIRCUIT_PARTNUMBER = "POW00004.ELEM";
   public static final String POF_ID_SCWCBP= "SPC00005.PROD";
   public static final String POF_ID_SCWKBP= "SPC00006.PROD";
   public static final String POF_ID_SCWMDBP= "SPC00007.PROD";
   public static final String POF_ID_SCWMKBP= "SPC00008.PROD";
  
   public static final String ASSET = "Asset";
   public static final String CABINET_DEMARC_ERROR_MESSAGE = "Cabinet #CABNUMBER# is not a valid Demarc Cabinet, expected Cabinet Type = Demarc found ";
   public static final String REPORT_MESSAGE_SENDER_QUEUE = "reportMessageSenderQueue";
   public static final String CAGE_MAX_NUMBER_CHECK_CAP = "CAGE_MAX_NUMBER_CHECK_CAP";
   
   public static final String POF_ID_PCWCBP= "SPC00001.PROD";
   public static final String POF_ID_PCWKBP= "SPC00002.PROD";
   public static final String POF_ID_PCWMDBP= "SPC00003.PROD";
   public static final String POF_ID_PCWMKBP= "SPC00004.PROD";
   public static final String IN_ACTIVE="InActive";
   public static final String ADD= "ADD";
   
	public static final String CIRCUITMAP = "CIRCUITMAP";
	public static final String CAGECABLIST = "CAGECABLIST";
	public static final String REQUESTCABQTY = "REQUESTCABQTY";
	public static final String DELETED_CABS = "DELETED_CABS";
	public static final String REQ_DRAW_CAB = "REQ_DRAW_CAB";
	public static final String REQ_CBP_CAB = "REQ_CBP_CAB";
	public static final String NUM_REDUNDANT_CIRUIT = "NUM_REDUNDANT_CIRUIT";
	public static final String REDUNDANT_KVA = "REDUNDANT_KVA";
	public static final String NUM_PRIMARY_CIRUIT = "NUM_PRIMARY_CIRUIT";
	public static final String PRIMARY_KVA = "PRIMARY_KVA";
	public static final String ASSETSTATUS = "ASSETSTATUS";
	public static final String EQXCABINETUSID = "EQXCABINETUSID";
	public static final String INSTALLATIONDATE = "INSTALLDATE";
	public static final String ASSETID = "ID";
	public static final String CUSTOMER_CABINET_REFERENCE_NUMBER = "CUSTOMER CABINET REFERENCE NUMBER";
	public static final String HEIGHT = "HEIGHT";
	public static final String WIDTH = "WIDTH";
	public static final String DEPTH = "DEPTH";
	public static final String CANCELLED="CANCELLED";
	public static final String EQXStatus="EQXStatus";
	public static final String EQXUniqueSpaceID="EQXUniqueSpaceID"	;
	public static final String Cabinet_Number="Cabinet Number";

	public static final String EXCEPTION_CODE_801 = "CL-801";
	public static final String EXCEPTION_CODE_901 = "CL-901";
	public static final String EXCEPTION_CODE_903 = "CL-903";
	public static final String EXCEPTION_CODE_202 = "CL-202";
	public static final String EXCEPTION_CODE_133 = "CL-133";
	public static final String ORDER_CANCEL_CIRCUIT_PRIMARY_REDUNDANT = "AC Type";
	public static final String EQXCapacityStatus = "EQXCapacityStatus";
	public static final String EQXNotes = "EQXNotes";
	public static final String CAPACITY_FOUND = "Capacity Found";
	public static final String Terminated = "Terminated";
	public static final String ORDER_COMPLETE = "Order Complete";	
	public static final String CFR_RESPONSE_INTERFACE_NAME = "CFR_Response";
	public static final String SALES_SITE_RATING_CAB_FAILURE_REASON = "Sales Site Rating violated for Cabinet #CABINET# Requested Power + In Progress Power + Installed Power Should be between Sales Site rating,Sales Site rating is #SALESRATING# (Picked from #ENTITYNAME#)";
	public static final String DRAW_CAP_FAIL_CABINET_REASON = "Draw Cap violated for Cabinet #CABINET# sum of Requested Power + In Progress Power + Installed Power should be less than Draw Cap of Cabinet. Draw Cap = #DRAWCAP#, Requested Power = #REQUESTEDPOWER#, In Progress Power = #INPROGRESSPOWER# and Installed Power =#INSTALLEDPOWER#";
	public static final String DRAW_CAP_KVA_FAIL_CABINET_REASON = "Draw Cap violated for Cabinet #CABINET# sum of Requested Power + In Progress Power + BCM Power should be less than Draw Cap of Cabinet. Draw Cap = #DRAWCAP#, Requested Power = #REQUESTEDPOWER#, In Progress Power = #INPROGRESSPOWER# and BCM Power =#INSTALLEDPOWER#";
	public static final String CBP_FAIL_CABINET_REASON = "CBP violated for Cabinet #CABINET# sum of Requested CBP + In Progress CBP + Installed CBP should be less than Max CBP. Max CBP = #MAXCBP#, Requested CBP = #REQUESTEDCBP#, In Progress CBP = #INPROGRESSCBP# and Installed CBP =#INSTALLEDCBP#";
	public static final String DRAW_CAP_FAIL_CAGE_REASON = "Draw Cap violated for Cage #CAGENUM# sum of Requested Power + In Progress Power + Installed Power should be less than Draw Cap. Draw Cap = #DRAWCAP#, Requested Power = #REQUESTEDPOWER#, In Progress Power = #INPROGRESSPOWER# and Installed Power =#INSTALLEDPOWER#";
	public static final String CBP_FAIL_CAGE_REASON = "CBP violated for Cage #CAGENUM# sum of Requested CBP + In Progress CBP + Installed CBP should be less than Max CBP. Max CBP = #MAXCBP#, Requested CBP = #REQUESTEDCBP#, In Progress CBP = #INPROGRESSCBP# and Installed CBP =#INSTALLEDCBP#";
	public static final String BUSINESS_PRODUCT_FAMILY="Business Continuity";
	public static final String BUSINESS_PRODUCT_FAMILY_WS="BusinessContinuity";
	public static final String COND_CIRCUIT_FAIL_CAGE_REASON = "Max Conditioned circuits violated for Cage #CAGENUM# sum of Requested circuits + In Progress circuits + Installed circuits should be less than Max Conditioned Circuits. Max Conditioned Circuits = #MAXCONDCIRCUIT#, Requested Conditioned Circuits = #REQUESTEDCONDCIRCUIT#, In Progress Conditioned Circuits = #INPROGRESSCONDCIRCUIT# and Installed Conditioned Circuits =#INSTALLEDCONDCIRCUIT#";
	public static final String UNCOND_CIRCUIT_FAIL_CAGE_REASON = "Max UnConditioned violated for Cage #CAGENUM# sum of Requested circuits + In Progress circuits + Installed circuits should be less than Max UnConditioned Circuits. Max UnConditioned Circuits = #MAXUNCONDCIRCUIT#, Requested UnConditioned Circuits = #REQUESTEDUNCONDCIRCUIT#, In Progress UnConditioned Circuits = #INPROGRESSUNCONDCIRCUIT# and Installed UnConditioned Circuits =#INSTALLEDUNCONDCIRCUIT#";
	public static final String CABINET_POF = "Pof";
	public static final String RELEASE_CAPACITY = "ReleaseCapacity";
	public static final String NETWORK_CFR_WORKFLOW_INTERFACE = "IS_NETWORK_CFR_SIEBEL_INTERFACE_AVAILABLE";
	public static final String NETWORK = "NETWORK";
	public static final String  EQX_CAGE_UNIQUE_SPACE_ID = "EQXCageUniqueSpaceId";
	public static final String CONFIG_KEY_PUBLISH_UNIQUESPACEID= "PUBLISH_UNIQUESPACEID";
	public static final String PUBLISH_USID_ON= "ON";
	public static final String POF_ID_EUBSWMPDC= "BS00001.PROD";
	public static final String POF_ID_NABS= "BS00003.PROD";
	public static final String POF_ID_EUBSWCBP= "BS00002.PROD";
	public static final String POF_ID_IBXSR= "SPC00009.PROD";
	public static final String POF_ID_IBXFLEX= "FLEX00001.PROD";
	public static final String EXCEPTION_CODE_904 = "CL-904";
	public static final String EXCEPTION_CODE_905 = "CL-905";
	public static final String EXCEPTION_CODE_906 = "CL-906";
	public static final String EXCEPTION_CODE_908 = "CL-908";
	public static final String INNERDUCT_PRODUCT_TYPE = "INNERDUCT_PRODUCT_TYPE";

	public static final String INNERDUCT_PORT_SAVE_EVENT_TYPE = "INNERDUCT_PORT_SAVE_EVENT_TYPE";
	public static final String INNERDUCT_PORT_SAVE_OR_RELEASE_SOURCE = "INNERDUCT_PORT_SAVE_OR_RELEASE_SOURCE";
	public static final String INNERDUCT_PORT_RELEASE_EVENT_TYPE = "INNERDUCT_PORT_RELEASE_EVENT_TYPE";
	public static final String INNERDUCT_PORT_RESERVATION_INTERFACE_AVAILABLE= "IS_INNERDUCT_PORT_RESERVATION_SIEBEL_INTERFACE_AVAILABLE";

	public static final String PENDING_CONVERSION = "Pending Conversion";

	public static final String EXCEPTION_CODE_907 = "CL-907";

	public static Double AREA_FACTOR_SQ_INCH_SQ_FEET=0.00694444;
	public static Double AREA_FACTOR_SQ_INCH_SQ_MTR=0.00064516;
	public static Double AREA_FACTOR_SQ_MM_SQ_FEET=0.0000107639104;
	public static Double AREA_FACTOR_SQ_MM_SQ_MTR=0.000001;
	public static final double HUNDRED_DOUBLE = 100.00;
	public static final String NOT_SUPPORTED_POF_PART_NUMBER = "NOT_SUPPORTED_POF_PART_NUMBER";
	public static final String EMPTY_STRING = "";
	public static final String OLD_CAB_USID_NOT_EXIST = "Old Cabinet USID provided doesn't exists in appops.";
	public static final String NEW_CAB_USID_NOT_EXIST = "New Cabinet USID provided doesn't exists in appops.";
	public static final String CAB_DOESNT_EXIST = "CABINET WITH PROVIDED UNIQUE SPACE ID DOESN'T EXISTS.";
	public static final String CUSTOMER_MISMATCH = "NEW CABINET AND OLD CABINET DOESN'T BELONG TO SAME CUSTOMER.";
	public static final String IN_PROGRESS_TNX = "NEW CABINET HAS TRANSACTION IN PROGRESS.";
	public static final String INCORRECT_CAB_CONFIG = "OLD CABINET SHOULD BE CONFIGURED AND NEW CABINET SHOULDN'T BE CONFIGURED.";
	public static final String UPDATE_ERROR = "ERROR UPDATING NEW CABINET.";
	public static final String CAB_USID_NOT_PRESENT = "OLD CABINET USID NOT PROVIDED OR NEW CABINET USID NOT PROVIDED.";

	public static final String XML_NON_SUPPORTED_BROWSER_MESSAGE = "NOT_SUPPORTED_BROWSER_MESSAGE";
	public static final String XML_CONTAINER_METHODS = "CONTAINER_METHODS";
	public static final String PARAM_CONFIG_KEY = "configKey";
	public static final String PARAM_CONFIG_VALUE = "configValue";
	public static final String CONFIG_KEY_MODE = "MODE";
	public static final String CONFIG_MODE_MAINTENANCE = "MAINTENANCE";
	public static final String CONFIG_MODE_PROD = "PROD";
	public static final String CONFIG_MAINTENANCE_PAGE_MSG = "MAINTENANCE_PAGE_MSG";
	public static final String CONFIG_KEY_GA_PRODUCT_CODE = "GA_PRODUCT_CODE";	
	public static final String CONFIG_KEY_GA_WEB_MONITORING = "GA_WEB_MONITORING";
	public static final String CONFIG_KEY_NEW_RELIC_WEB_MONITORING = "NEW_RELIC_WEB_MONITORING";
	public static final String OFF = "OFF";
	public static final String ON = "ON";	
	
	//XSD-XSLT framework
	public static final String COLO_INITIATE_CFR_REQUEST_PAYLOAD_XSLT="coloCFRPayload";
	public static final String COLO_DELETE_CAPACITY_REQ_MAPPER_XSLT = "ColoDeleteCapacityRequestMapper";
	public static final String COLO_INITIATE_CFR_PAYLOAD_XSLT="payload";
	public static final String COLO_CHECK_CAPACITY_REQUEST_MAPPER_XSLT = "ColoCheckCapacityRequestMapper";
	public static final String  COLO_ORDER_BOOKED_MAPPER = "ColoOrderBookedRequestMapper";
	public static final String  COLO_ORDER_COMPLETE_MAPPER = "ColoOrderCompleteRequestMapper";
	public static final String  COLO_ORDER_CANCEL_MAPPER = "ColoOrderCancelRequestMapper";
	public static final String  QUOTE_STATUS_NOTIFICATION_MAPPER = "QuoteStatusNotificationMapper";
	public static final String APPOPS_COMMON_XSLT = "AppOps_Common";
	public static final String PARAM_XML_FILE_NAME = "xmlFileName";
	public static final String NETWORK_CHECK_CAPACITY_REQ_MAPPER_XSLT = "NetworkCheckCapacityRequestMapper";
	public static final String NETWORK_CFR_PAYLOAD_XSLT = "networkCFRPayload";
	public static final String NETWORK_PAYLOAD_XSLT = "networkpayload";
	public static final String INNERDUCT_CFR_PAYLOAD_XSLT = "InnerductCFRPayload";
	public static final String INNERDUCT__PAYLOAD_XSLT = "innerductpayload";
	public static final String NETWORK_DELETE_CAPACITY_REQ_MAPPER_XSLT = "NetworkDeleteCapacityRequestMapper";
	public static final String  NETWORK_ORDER_BOOKED_MAPPER = "NetworkOrderBookedRequestMapper";
	public static final String  NETWORK_ORDER_COMPLETE_MAPPER = "NetworkOrderCompleteRequestMapper";
	public static final String  NETWORK_ORDER_CANCEL_MAPPER = "NetworkOrderCancelRequestMapper";
	public static final String NETWORK_RESERVE_CAPACITY_REQ_MAPPER_XSLT = "NetworkReserveCapacityRequestMapper";
	public static final String COLO_RESERVE_CAPACITY_REQUEST_MAPPER_XSLT = "ColoReserveCapacityRequestMapper";
	public static final String COLO_CHECK_CONFIG_REQUEST_MAPPER_XSLT = "ColoCheckConfigurationRequestMapper";
	public static final String  NETWORK_WORK_UPDATE_ORDER_MAPPER = "NetworkWorkOrderUpdateRequestMapper";
	public static final String RELEASE_CAPACITY_XSD = "ReleaseCapacity";
	public static final String TIBCO_ASYN_ACK_MESSAGE_XSD = "TibcoAsynAckMessage";
	public static final String QUOTE_REQUEST_XSD = "QuoteRequest";
	public static final String QUOTE_RESPONSE_XSD = "QuoteResponse";
	public static final String ORDER_REQUEST_XSD = "OrderRequest";
	public static final String ORDER_RESPONSE_XSD = "OrderResponse";
	public static final String ORDER_COMPLETE_XSD = "OrderCompleteRequest";
	public static final String RESOURCE_OUT_SYNC_MESSAGE_FILE_LOC = "RESOURCE_OUT_SYNC_MESSAGE_FILE_LOC";
	
	public static final String PAYLOAD_REQUEST_LOGGER_ORDER_BOOKED="PAYLOAD_REQUEST_LOGGER_ORDER_BOOKED";
	public static final String PAYLOAD_REQUEST_LOGGER_ORDER_CANCEL="PAYLOAD_REQUEST_LOGGER_ORDER_CANCEL";
	public static final String PAYLOAD_REQUEST_LOGGER_ORDER_COMPLETE="PAYLOAD_REQUEST_LOGGER_ORDER_COMPLETE";
	public static final String PAYLOAD_REQUEST_LOGGER_QUOTE_STATUS_NOTIFICATION="PAYLOAD_REQUEST_LOGGER_QUOTE_STATUS_NOTIFICATION";
	public static final String PAYLOAD_REQUEST_LOGGER_UPDATE_WORK_ORDER="PAYLOAD_REQUEST_LOGGER_UPDATE_WORK_ORDER";
	public static final String SYS_PARAM_PK_ID_KEY = "pkIdKey";
	
	public static final String EMAIL_TEMPLATE_GROUP = "EMAIL";
	public static final String BROWSER_MESSAGE_GROUP = "BROWSER";
	public static final String REFRESH_CONTAINER_GROUP = "REFRESH";
	public static final String RESOURCE_GROUP = "RESOURCE";
	public static final String XSD_GROUP = "XSD";
	public static final String XSLT_GROUP = "XSLT";
	public static final String PARAM_XML_DATA_VALUE = "xmlDataValue";
	public static final String SYS_PARAM_KEY = "groupName";
	public static final String SYS_PARAM_VALUE = "value";

	public static final String INPROGRESS_CAGE_UNIQUE_SPACE_ID = "USID_ID";
	public static final String INPROGRESS_CABINET_UNIQUE_SPACE_ID = "USID_ID";	
	public static final String INPROGRESS_CKT_CABINET_NUM = "CABINET NUMBER";
	public static final String INPROGRESS_CKT_TYPE = "TYPE";
	public static final String INPROGRESS_CKT_PHASE = "PHASE";
	public static final String INPROGRESS_CKT_AMPS = "SOLD AMPERAGE";
	public static final String INPROGRESS_CKT_VOLTS = "VOLTAGE";
	public static final String INPROGRESS_CKT_CAGE_UNQ_SPACE_ID = "UNIQUE SPACE ID";
	public static final String INPROGRESS_CKT_AC_CIRCUIT_PRODUCT = "AC CIRCUIT";
	public static final String INPROGRESS_CKT_DC_CIRCUIT_PRODUCT = "DC CIRCUIT";
	public static final String INPROGRESS_SPACE_TYPE= "SPACE TYPE";
	public static final String INPROGRESS_PRIVATE_CAGE= "PRIVATE CAGE";
	public static final String INPROGRESS_SECURED_CABINET= "SECURED CABINET";
	public static final String INPROGRESS_NA_BUSINESS_SUITE= "NA BUSINESS SUITE";
	public static final String INPROGRESS_EU_BUSINESS_SUITE = "EU BUSINESS SUITE";

	public static final String QUOTE_REVERSION_CFR_REJECT="In-Progress CFR is cancelled via Quote Reversion";
	public static final String QUOTE_REVERSION_REJECT_APPROVED_CFR="Capacity is released for a Approved CFR by Quote Reversion";
	public static final String POWER_CIRCUIT = "Power Circuit";
	public static final String CONTRACTED_KVA = "contractedKVA";
	public static final String CONTRACTED_CABE = "contractedCabe";
	public static final String BCTR_UNIQUE_SPACE_ID = "BCTR Unique Space Id";
	public static final String WORKSTATION_NUMBER = "Workstation Number";
	public static final String EXCEPTION_CODE_909 = "CL-909";
	public static final String EXCEPTION_CODE_910 = "CL-910";
	public static final String EXCEPTION_CODE_911 = "CL-911";
	public static final String VALID = "Valid";
	public static final String INVALID = "Invalid";
	public static final String ANTENNA_POWER_TYPE = "ANTENNA_POWER_TYPE";
	public static final String LOCATION = "LOCATION";
	public static final String COMPLETED = "Completed";
	public static final String IBX_PRODUCT_ENFORCE_CFR_REASON = "#IBX# for product #PRODUCT# is enforced for Space/Power CFR";
	public static final String CFR_THRESHOLD_DRAWCAP_CABE = "Cabinet Threshold for IBX #IBX# and Product #PRODUCT# violated: Cabinet threshold #CABETH#. Requested Value: Cabinet #CABREQ#";
	public static final String IBX_PRODUCT_SALESSITERATING_CFRREASON = "Draw cap per Cabinet violates sales site rating of IBX #IBX#. Requested Draw cap : #DRAWCAP# . Requested Cabinet : #REQCABE# . Min Sales site rating of IBX: #SALESMIN# and Max Sales site rating of IBX: #SALESMAX# ";
	public static final String EXCEPTION_CODE_912 = "CL-912";
	public static final String EXCEPTION_CODE_913 = "CL-913";
	public static final String QUOTE_STATUS_CFR_REJECT="In-Progress CFR is rejected via Quote Status Notification";
	public static final String CAGE_RECONFIG_REDUCTION_TYPE = "Reduction";
	public static final String RECONFIG_CAGE_REDUCTION_TYPE = "CAGE_REDUCTION";
	public static final String REDUCTION = "Reduction";
	public static final String FILE_PUBLISHER = "uploadCageCabinetFilePublisher";
	public static final String IS_MOVE_RESERVATION_SIEBEL_INTERFACE_AVAILABLE = "IS_MOVE_RESERVATION_SIEBEL_INTERFACE_AVAILABLE";
	public static final String IS_MOVE_RESERVATION_SIEBEL_VIEW_AVAILABLE = "IS_MOVE_RESERVATION_SIEBEL_VIEW_AVAILABLE";
	
	public static final String SEND_EMAIL_NOTIFICATION = "SEND_EMAIL_NOTIFICATION";
	public static final String ON_VALUE = "ON";
	public static final String MAIL_SERVER_HOST_HEADER = "MAIL_SERVER_HOST_HEADER";
	public static final String MAIL_SERVER_HOST_VALUE = "MAIL_SERVER_HOST_VALUE";
	public static final String MAIL_SERVER_PORT_HEADER = "MAIL_SERVER_PORT_HEADER";
	public static final String MAIL_SERVER_PORT_VALUE = "MAIL_SERVER_PORT_VALUE";
	public static final String MAIL_SERVER_AUTH_HEADER = "MAIL_SERVER_AUTH_HEADER";
	public static final String MAIL_SERVER_SMTP_HEADER = "MAIL_SERVER_SMTP_HEADER";
	public static final String MAIL_SERVER_SMTP_HEADER_VALUE ="MAIL_SERVER_SMTP_HEADER_VALUE";
	public static final String MAIL_SERVER_SMTP_PROTOCOL_HEADER = "MAIL_SERVER_SMTP_PROTOCOL_HEADER";
	public static final String MAIL_SERVER_SMTP_SSL_TRUST_HEADER = "MAIL_SERVER_SMTP_SSL_TRUST_HEADER";
	public static final String MAIL_SERVER_SMTP_SSL_IDENTITY_HEADER = "MAIL_SERVER_SMTP_SSL_IDENTITY_HEADER";
	public static final String MAIL_SERVER_SMTP_TLS_HEADER = "MAIL_SERVER_SMTP_TLS_HEADER";
	public static final String MAIL_SERVER_USERNAME = "MAIL_SERVER_USERNAME";
	public static final String MAIL_SERVER_PASSWORD = "MAIL_SERVER_PASSWORD";
	public static final String MAIL_SERVER_AUTH_VALUE = "MAIL_SERVER_AUTH_VALUE";
	public static final String MAIL_SERVER_SMTP_TLS_VALUE = "MAIL_SERVER_SMTP_TLS_VALUE";
	public static final String MAIL_SERVER_SMTP_PROTOCOL_VLAUE = "MAIL_SERVER_SMTP_PROTOCOL_VLAUE";
	public static final String MAIL_SERVER_DEBUG_HEADER = "MAIL_SERVER_DEBUG_HEADER";
	public static final String MAIL_SERVER_DEBUG_VALUE= "MAIL_SERVER_DEBUG_VALUE";
	public static final String MAIL_SERVER_SMTP_SSL_TRUST_VALUE= "MAIL_SERVER_SMTP_SSL_TRUST_VALUE";
	public static final String MAIL_SERVER_SMTP_SSL_IDENTITY_VALUE= "MAIL_SERVER_SMTP_SSL_IDENTITY_VALUE";
	public static final String MAIL_SERVER_EMAIL_TOKENS= "MAIL_SERVER_EMAIL_TOKENS";
	public static final String MAIL_SERVER_EMAIL_CONTENT_TYPE= "MAIL_SERVER_EMAIL_CONTENT_TYPE";
	public static final String MAIL_AUTH_TRUE= "true";
	public static final String LOGO_PATH= "LOGO_PATH";
	public static final String LOGO_PATH_WHITE= "LOGO_PATH_WHITE";

	public static final String EXCEPTION_CODE_914 = "CL-914";
	public static final String EXCEPTION_CODE_915 = "CL-915";
	
	public static final String EMAIL_SENDER_QUEUE = "emailSenderQueue";
	public static final String DOCKER_SENDER_QUEUE = "dockerSenderQueue";
	public static final String ELASTIC_BROKER_QUEUE = "elasticBrokerQueue";
	public static final String MAINTENANCE_QUEUE = "maintenanceQueue";
	
	public static final String CLX_KAFKA_TOPIC_CONSUMER_FLAG = "CLX_KAFKA_TOPIC_CONSUMER_FLAG";
	public static final String SBL_KAFKA_TOPIC_CONSUMER_FLAG = "SBL_KAFKA_TOPIC_CONSUMER_FLAG";
	public static final String SV_KAFKA_TOPIC_CONSUMER_FLAG = "SV_KAFKA_TOPIC_CONSUMER_FLAG";
	
	public static final String DFRCANCELLED="Cancelled";
	public static final String SYNCERROR="Sync Error";
	public static final String SYNCINPROGRESS="Sync In Progress";
	public static final String SYNCCOMPLETED="Completed";
	public static final String SYNCPARTIALLYCOMPLETED="Partially Completed";
	public static final String SYNCNOTREQUIRED="NR";
	public static final String CLX_PRODUCT = "CLX";
	public static final String SBL_PRODUCT = "SBL";
	public static final String DFR_EMAIL_NOTIFICATION_FLAG = "DFR_EMAIL_NOTIFICATION_FLAG";
	public static final String DFR_RETRY_INTEGRATION_FLAG = "DFR_RETRY_INTEGRATION_FLAG";
	public static final String EMAIL_MESSAGE_PUSHED = "EMAIL PUSHED INTO TOPIC";
	public static final String EMAIL_MESSAGE_NOT_PUSHED = "EMAIL NOT PUSHED INTO TOPIC";
	public static final String EMAIL_MESSAGE_CONSUMED = "EMAIL CONSUMED FROM TOPIC";
	public static final String EMAIL_MESSAGE_DELIVERED = "EMAIL_MESSAGE_DELIVERED";
	public static final String EMAIL_MESSAGE_UNDELIVERED = "EMAIL_NOT MESSAGE SEND";
	public static final String FAILURE_EMAIL_RETRY_INTEGRATION_FLAG = "FAILURE_EMAIL_RETRY_INTEGRATION_FLAG";
	public static final String CLX_EXCLUDED_TAG_LIST = "CLX_EXCLUDED_TAG_LIST";
	public static final String PHYSICAL_AUDIT_INTIATE="Physical Audit Initiated";
	public static final String PHYSICAL_AUDIT_IMPORT="Physical Audit Import Successful";
	public static final String EDIT_DFR_IMPORT="Edit DFR Import Successful";
	public static final String DFR_VALIDATE="Validated";
	public static final String DFR_INITIATED="New";
	public static final String DFR_SAVE="Saved";
	public static final String DFR_CANCEL="Cancelled";
	public static final String NOCC_PRODUCT="NOCC";
}


