
package com.intecbilling.tresoap._2_0.afs_inbound;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AFS-Inbound", targetNamespace = "http://tresoap.intecbilling.com/2.0/AFS-Inbound", wsdlLocation = "http://10.193.153.115:51111/services/AFS-Inbound?wsdl")
public class AFSInbound
    extends Service
{

    private final static URL AFSINBOUND_WSDL_LOCATION;
    private final static WebServiceException AFSINBOUND_EXCEPTION;
    private final static QName AFSINBOUND_QNAME = new QName("http://tresoap.intecbilling.com/2.0/AFS-Inbound", "AFS-Inbound");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.193.153.115:51111/services/AFS-Inbound?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AFSINBOUND_WSDL_LOCATION = url;
        AFSINBOUND_EXCEPTION = e;
    }

    public AFSInbound() {
        super(__getWsdlLocation(), AFSINBOUND_QNAME);
    }

    public AFSInbound(WebServiceFeature... features) {
        super(__getWsdlLocation(), AFSINBOUND_QNAME, features);
    }

    public AFSInbound(URL wsdlLocation) {
        super(wsdlLocation, AFSINBOUND_QNAME);
    }

    public AFSInbound(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AFSINBOUND_QNAME, features);
    }

    public AFSInbound(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AFSInbound(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AFSInboundPortType
     */
    @WebEndpoint(name = "AFS-InboundHttpSoap11Endpoint")
    public AFSInboundPortType getAFSInboundHttpSoap11Endpoint() {
        return super.getPort(new QName("http://tresoap.intecbilling.com/2.0/AFS-Inbound", "AFS-InboundHttpSoap11Endpoint"), AFSInboundPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AFSInboundPortType
     */
    @WebEndpoint(name = "AFS-InboundHttpSoap11Endpoint")
    public AFSInboundPortType getAFSInboundHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://tresoap.intecbilling.com/2.0/AFS-Inbound", "AFS-InboundHttpSoap11Endpoint"), AFSInboundPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AFSINBOUND_EXCEPTION!= null) {
            throw AFSINBOUND_EXCEPTION;
        }
        return AFSINBOUND_WSDL_LOCATION;
    }

}
