
package com.intecbilling.tresoap._2_0.afs_inbound;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AFS-InboundPortType", targetNamespace = "http://tresoap.intecbilling.com/2.0/AFS-Inbound")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.intecbilling.tresoap._2_0.afs_inbound.ObjectFactory.class,
    com.intecbilling.tresoap.fault._2.ObjectFactory.class
})
public interface AFSInboundPortType {


    /**
     * Guided to fEQX_in_AFS_ProcessOrder& [1]
     * 
     * @param parameters
     * @return
     *     returns com.intecbilling.tresoap._2_0.afs_inbound.ProcessOrderResponse
     * @throws ConnectionFault
     */
    @WebMethod(operationName = "ProcessOrder", action = "urn:ProcessOrder")
    @WebResult(name = "ProcessOrderResponse", targetNamespace = "http://tresoap.intecbilling.com/2.0/AFS-Inbound", partName = "parameters")
    public ProcessOrderResponse processOrder(
        @WebParam(name = "ProcessOrderRequest", targetNamespace = "http://tresoap.intecbilling.com/2.0/AFS-Inbound", partName = "parameters")
        ProcessOrderRequest parameters)
        throws ConnectionFault
    ;

}
