
package com.intecbilling.tresoap._2_0.afs_inbound;

import javax.xml.ws.WebFault;
import com.intecbilling.tresoap.fault._2.ConnectionFaultDetail;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ConnectionFault", targetNamespace = "http://tresoap.intecbilling.com/fault/2.0")
public class ConnectionFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ConnectionFaultDetail faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ConnectionFault(String message, ConnectionFaultDetail faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ConnectionFault(String message, ConnectionFaultDetail faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.intecbilling.tresoap.fault._2.ConnectionFaultDetail
     */
    public ConnectionFaultDetail getFaultInfo() {
        return faultInfo;
    }

}
